### PR TITLE
Anton can compile tbb on a mac 

### PR DESCRIPTION
**Pull request by antonleykin**
I still needed to get 
`wget https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2020.3.tar.gz`
This version compiles on my old mac (Catalina).

### CODE REVIEW

**Comment by DanGrayson** [comment]
Thanks.  I've uploaded that tarfile and updated the makefile so the tar file can be gotten automatically.

But it still doesn't compile for me.  Same problem as before!

**Comment by antonleykin** [comment]
Hi Dan,

I managed to build on ubuntu after getting rid of tbb on the system. It
required pointing to the correct directories in the fashion below.
Could you suggest how to modify the M2 makefile for building tbb, so that
necessary things are linked to the usr-host/... ?

Cheers,
--Anton

***@***.***:~/M2repos/anton-add-library-tbb/M2/BUILD/dan/builds.tmp/cos-3m2467-add-library-tbb$
export LD_LIBRARY_PATH=\
/home/aleykin3/M2repos/anton-add-library-tbb/M2/BUILD/dan/builds.tmp/cos-3m2467-add-library-tbb/libraries/tbb/build/oneTBB-2020\
.3/build/linux_intel64_gcc_cc9.3.0_libc2.31_kernel5.4.72_release

***@***.***:~/M2repos/anton-add-library-tbb/M2/BUILD/dan/builds.tmp/cos-3m2467-add-library-tbb$
'/home/aleykin3/M2repos\
/anton-add-library-tbb/M2/configure'  '--enable-encap' '--enable-download'
'--enable-strip' '--enable-deb' '--enable-build-libr\
aries=cohomcalg tbb' 'CC=cc' 'CXX=g++' 'FC=gfortran' 'AR=ar' 'CPPFLAGS=-I
/home/aleykin3/M2repos/anton-add-library-tbb/M2/BUILD\
/dan/builds.tmp/cos-3m2467-add-library-tbb/libraries/tbb/build/oneTBB-2020.3/include'
'LDFLAGS=-L /home/aleykin3/M2repos/anton-\
add-library-tbb/M2/BUILD/dan/builds.tmp/cos-3m2467-add-library-tbb/libraries/tbb/build/oneTBB-2020.3/build/linux_intel64_gcc_cc\
9.3.0_libc2.31_kernel5.4.72_release' '--prefix=/usr'
'--build=x86_64-pc-linux-gnu' 'build_alias=x86_64-pc-linux-gnu'

**Comment by DanGrayson** [comment]
I could do that for you.  Which version of Ubuntu was it?  Did you compile on my branch?

**Comment by antonleykin** [comment]
ubuntu 20.04
It was almost your branch, I just sent another pull request.

**Pull request merged**
